// Offline curator review sheet: every verified café with its current five-axis
// curator scores, neighborhood, and review state, as a markdown table.
// Idempotent read-only pass over the LOCAL D1 database (same file `npm run
// preview` serves). Prereq: `npm run db:migrate:local` + `npm run seed`.
// Run: npx tsx scripts/score-review-sheet.ts [out.md]   (default: docs/score-review-sheet.md)
import { writeFileSync } from "node:fs"
import { openLocalD1 } from "./local-d1"
import { CafeRepository } from "../lib/db/repositories/cafes"
import { ScoreRepository } from "../lib/db/repositories/scores"
import { SCORE_AXES } from "../lib/schemas/score"
import type { Cafe } from "../lib/schemas/cafe"
import type { CafeScore } from "../lib/schemas/score"

const AXIS_HEADERS: Record<(typeof SCORE_AXES)[number], string> = {
  quality: "Quality",
  priceValue: "Price/value",
  workFriendliness: "Work",
  quietVibe: "Quiet",
  specialtyDepth: "Specialty",
}

export function renderReviewSheet(
  rows: { cafe: Cafe; score: CafeScore | null }[],
  generatedAt: string,
): string {
  const sorted = [...rows].sort((a, b) => {
    const ra = a.score?.scoresReviewedAt ? 1 : 0
    const rb = b.score?.scoresReviewedAt ? 1 : 0
    return ra - rb || a.cafe.name.localeCompare(b.cafe.name)
  })
  const reviewed = sorted.filter((r) => r.score?.scoresReviewedAt).length
  const unreviewed = sorted.filter((r) => !r.score?.scoresReviewedAt)

  const header = [
    "Café",
    "Neighborhood",
    ...SCORE_AXES.map((a) => AXIS_HEADERS[a]),
    "Reviewed",
    "Notes",
  ]
  const lines = [
    "# Curator score review sheet",
    "",
    `Generated ${generatedAt} from local D1. ${reviewed} / ${sorted.length} reviewed.`,
    "",
    "Walk each row, adjust axes in /admin → Café scores, then “Save & mark reviewed”.",
    "Scores are drafts until the Reviewed column shows a date. Do not edit this file to approve.",
    "",
    `| ${header.join(" | ")} |`,
    `| ${header.map(() => "---").join(" | ")} |`,
    ...sorted.map(({ cafe, score }) => {
      const axes = SCORE_AXES.map((a) => (score ? String(score[a]) : "—"))
      const reviewedAt = score?.scoresReviewedAt ? score.scoresReviewedAt.slice(0, 10) : "no"
      return `| ${cafe.name} (\`${cafe.slug}\`) | ${cafe.neighborhood ?? "?"} | ${axes.join(" | ")} | ${reviewedAt} |  |`
    }),
    "",
    "## Still unreviewed",
    "",
    ...(unreviewed.length === 0
      ? ["_none — every live café is curator-reviewed._"]
      : unreviewed.map(({ cafe }) => `- ${cafe.name} (\`${cafe.slug}\`)`)),
    "",
  ]
  return lines.join("\n")
}

async function main() {
  const out = process.argv[2] ?? "docs/score-review-sheet.md"
  const db = openLocalD1()
  const cafes = await new CafeRepository(db).findVerified()
  const scores = await new ScoreRepository(db).findForCafes(cafes.map((c) => c.id))
  const rows = cafes.map((cafe) => ({ cafe, score: scores.get(cafe.id) ?? null }))
  const md = renderReviewSheet(rows, new Date().toISOString().slice(0, 10))
  writeFileSync(out, md)
  const reviewed = rows.filter((r) => r.score?.scoresReviewedAt).length
  console.log(`wrote ${out}: ${rows.length} verified cafés, ${reviewed} reviewed`)
}

if (process.argv[1]?.endsWith("score-review-sheet.ts")) {
  main().catch((err) => {
    console.error("REVIEW SHEET FAILED:", err)
    process.exit(1)
  })
}
