// Idempotent seed of curated cafés + curator scores from data/seed/*.json.
// Applies to the LOCAL D1 database (the file `npm run preview` serves) and
// writes scripts/seed-cafes.sql for remote application:
//   wrangler d1 execute radaroma --remote --file=scripts/seed-cafes.sql
//
// Re-running converges: cafes upsert by slug (never downgrading status),
// scores upsert by (cafe_id, scored_by).
import { readFileSync, readdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { randomUUID } from "node:crypto"
import { z } from "zod"
import { openLocalD1 } from "./local-d1"
import { nowIso } from "../lib/db/sql"
import { CafeRepository } from "../lib/db/repositories/cafes"
import { ScoreRepository } from "../lib/db/repositories/scores"
import { ScoreInputSchema } from "../lib/schemas/score"

const SeedCafeSchema = z.object({
  slug: z.string().regex(/^[a-z0-9-]+$/, "slug must be kebab-case"),
  name: z.string().min(1),
  address: z.string().min(1),
  lat: z.number(),
  lng: z.number(),
  neighborhood: z.string().min(1),
  priceTier: z.number().int().min(1).max(4),
  scores: ScoreInputSchema,
  notes: z.string().optional().default(""),
})
type SeedCafe = z.infer<typeof SeedCafeSchema>

const sqlLiteral = (v: string): string => `'${v.replaceAll("'", "''")}'`

async function main() {
  const seedDir = "data/seed"
  const entries: SeedCafe[] = []
  for (const file of readdirSync(seedDir).filter((f) => f.endsWith(".json"))) {
    const parsed = JSON.parse(readFileSync(join(seedDir, file), "utf8"))
    const validated = z.array(SeedCafeSchema).parse(parsed)
    console.log(`${file}: ${validated.length} cafés`)
    entries.push(...validated)
  }
  if (entries.length === 0) throw new Error("no seed data found in data/seed/")

  const seen = new Set<string>()
  for (const e of entries) {
    if (seen.has(e.slug)) throw new Error(`duplicate slug in seed data: ${e.slug}`)
    seen.add(e.slug)
  }

  const db = openLocalD1()
  const cafes = new CafeRepository(db)
  const scores = new ScoreRepository(db)

  const statements: string[] = [
    "-- generated by scripts/seed-cafes.ts — idempotent upserts",
  ]
  let upserted = 0

  for (const e of entries) {
    const now = nowIso()
    await db.run(
      `insert into cafes (
        id, slug, name, address, lat, lng, neighborhood, price_tier, source,
        status, confidence_score, verification_notes, created_at, updated_at
      ) values (?, ?, ?, ?, ?, ?, ?, ?, 'owner', 'verified', NULL, ?, ?, ?)
      on conflict (slug) do update set
        name = excluded.name,
        address = excluded.address,
        lat = excluded.lat,
        lng = excluded.lng,
        neighborhood = excluded.neighborhood,
        price_tier = excluded.price_tier,
        verification_notes = excluded.verification_notes,
        updated_at = excluded.updated_at`,
      [
        randomUUID(),
        e.slug,
        e.name,
        e.address,
        e.lat,
        e.lng,
        e.neighborhood,
        e.priceTier,
        e.notes,
        now,
        now,
      ],
    )
    const cafe = await cafes.findBySlug(e.slug)
    if (!cafe) throw new Error(`seed: cafe not found after upsert: ${e.slug}`)
    await scores.upsertCurator(cafe.id, e.scores)
    upserted += 1

    const s = (v: number | null): string => (v === null ? "NULL" : String(v))
    statements.push(
      `insert into cafes (id, slug, name, address, lat, lng, neighborhood, price_tier, source, status, confidence_score, verification_notes, created_at, updated_at)
 values (${sqlLiteral(randomUUID())}, ${sqlLiteral(e.slug)}, ${sqlLiteral(e.name)}, ${sqlLiteral(e.address)}, ${s(e.lat)}, ${s(e.lng)}, ${sqlLiteral(e.neighborhood)}, ${e.priceTier}, 'owner', 'verified', NULL, ${sqlLiteral(e.notes)}, ${sqlLiteral(now)}, ${sqlLiteral(now)})
 on conflict (slug) do update set name = excluded.name, address = excluded.address, lat = excluded.lat, lng = excluded.lng, neighborhood = excluded.neighborhood, price_tier = excluded.price_tier, verification_notes = excluded.verification_notes, updated_at = excluded.updated_at;`,
    )
    statements.push(
      `insert into cafe_scores (id, cafe_id, scored_by, quality, price_value, work_friendliness, quiet_vibe, specialty_depth, updated_at)
 values (${sqlLiteral(randomUUID())}, (select id from cafes where slug = ${sqlLiteral(e.slug)}), 'curator', ${e.scores.quality}, ${e.scores.priceValue}, ${e.scores.workFriendliness}, ${e.scores.quietVibe}, ${e.scores.specialtyDepth}, ${sqlLiteral(now)})
 on conflict (cafe_id, scored_by) do update set quality = excluded.quality, price_value = excluded.price_value, work_friendliness = excluded.work_friendliness, quiet_vibe = excluded.quiet_vibe, specialty_depth = excluded.specialty_depth, updated_at = excluded.updated_at;`,
    )
  }

  writeFileSync("scripts/seed-cafes.sql", statements.join("\n") + "\n")

  const total = await db.get<{ n: number }>("select count(*) as n from cafes where status = 'verified'")
  console.log(`upserted ${upserted} cafés + scores into local D1`)
  console.log(`verified cafés in DB now: ${total?.n ?? 0}`)
  console.log("remote SQL written to scripts/seed-cafes.sql")
}

main().catch((err) => {
  console.error("SEED FAILED:", err)
  process.exit(1)
})
